### ISSUE TITLE
angular

### ISSUE THREAD

**Issue by mictadlo** [unboundedsystems/typescript-docker-vscode-build-hello#1]
Hi,
How would you change your code for Angular?

Thank you in advance,

Michal

**Comment by mvachhar** [comment]
Could you be more specific?  I'm not an angular user so I don't know the details.  Can you just include the Angular package?  Are there specific angular command line tools required?

**Comment by mictadlo** [comment]
I tried this one but I got the following error:

```
./bin/node install @angular/cli -g
Unable to find image 'node:8' locally
8: Pulling from library/node
61be48634cb9: Pull complete 
fa696905a590: Pull complete 
b6dd2322bbef: Pull complete 
32477089adb4: Pull complete 
febe7209ec28: Pull complete 
4364cbe57162: Pull complete 
ace5c680ff94: Pull complete 
4acd6a9b7a48: Pull complete 
Digest: sha256:7b65413af120ec5328077775022c78101f103258a1876ec2f83890bce416e896
Status: Downloaded newer image for node:8
module.js:550
    throw err;
    ^

Error: Cannot find module '/src/install'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

What did I miss?

Thank you in advance,

Michal

**Comment by mvachhar** [comment]
Does npm install work, vs. node install?

**Comment by mterrel** [comment]
Typically, in our projects, we'll create a soft link to `npm` like this:
```
cd bin
ln -s node npm
cd ..
```
Now, you should be able to do:
```
./bin/npm install @angular/cli -g
```
(Note that if you're just running this directly out of a clone of this repo, the `npm` soft link already exists in ./bin)

**Comment by mictadlo** [comment]
Thank you it works.
